# Generated by Django 2.2 on 2021-09-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trial_count',
            field=models.IntegerField(default=30, verbose_name='试用次数'),
        ),
    ]
