# Generated by Django 2.2 on 2021-09-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_trial_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trial_count',
            field=models.IntegerField(default=2, verbose_name='试用次数'),
        ),
    ]
