# Generated by Django 2.2 on 2021-12-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211109_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ig_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ig_token',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Instagram token'),
        ),
    ]
