# Generated by Django 2.2 on 2022-01-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_pricing_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trial_count',
            field=models.IntegerField(default=5, verbose_name='试用次数'),
        ),
    ]
