# Generated by Django 2.2 on 2021-08-13 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.CharField(max_length=600, verbose_name='描述')),
                ('result', models.CharField(max_length=800, verbose_name='结果')),
            ],
            options={
                'verbose_name': '用户产品描述',
                'verbose_name_plural': '用户产品描述',
            },
        ),
    ]
