# Generated by Django 2.2 on 2021-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0002_userproductdesc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductdesc',
            name='product_type',
            field=models.CharField(default='', max_length=200, verbose_name='产品类型'),
        ),
    ]
