# Generated by Django 2.2 on 2021-09-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0003_userproductdesc_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproductdesc',
            name='trial_count',
            field=models.IntegerField(default=30, verbose_name='试用次数'),
        ),
    ]
