# Generated by Django 2.2 on 2021-09-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0004_userproductdesc_trial_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductdesc',
            name='trial_count',
        ),
    ]
