# Generated by Django 2.2 on 2021-09-04 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0005_remove_userproductdesc_trial_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProductDesc',
        ),
    ]
