# Generated by Django 2.2 on 2021-09-04 23:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copywriting', '0008_delete_userproductdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.CharField(max_length=600, verbose_name='描述')),
                ('product_type', models.CharField(default='', max_length=200, verbose_name='产品类型')),
                ('result_link', models.URLField(verbose_name='结果')),
                ('thumb_up', models.BooleanField(blank=True, default=False, verbose_name='赞')),
                ('thumb_down', models.BooleanField(blank=True, default=False, verbose_name='踩')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户产品描述',
                'verbose_name_plural': '用户产品描述',
            },
        ),
    ]
