# Generated by Django 2.2 on 2021-11-18 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0009_userproductdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductdesc',
            name='add_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='添加时间'),
        ),
    ]
