# Generated by Django 2.2 on 2022-01-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copywriting', '0014_instagrammedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrammedia',
            name='caption',
            field=models.CharField(default='', max_length=500, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='instagrammedia',
            name='url',
            field=models.URLField(default='', max_length=400, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='instagrammedia',
            name='media_id',
            field=models.CharField(default='', max_length=200, verbose_name='media_id'),
        ),
    ]
